name: Build 🔧

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # Get the code
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        submodules: true

    # Setup environment
    - name: Install Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version: '^1.18.3'
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        registry-url: https://registry.npmjs.org/
    - name: Install Hugo
      uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3
      with:
        hugo-version: '0.101.0'

    # Install dependencies
    - name: Install Deps 🌎
      run: |
        npm install
        go install github.com/gauntface/go-html-asset-manager/v5/cmds/htmlassets@latest
        go install github.com/gauntface/go-html-asset-manager/v5/cmds/genimgs@latest
        go install github.com/tdewolff/minify/v2/cmd/minify@latest
    - name: Build 🔧
      run: npm run build
    - name: Docker 🐳
      run: make docker-build
