name: Release 🚀

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    # Get the code
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        submodules: true

    - name: Log in to the Container registry
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@a64d0487d7069df33b279515d35d60fa80e2ea62
      with:
        images: ghcr.io/gauntface/printboy

    - name: Build and push Docker image
      uses: docker/build-push-action@bca5082da7f40c0685bc546726266df13a2f9f4b
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

